function R = euler2R(l)
% returns the rotation matrix for a given vector of euler angles

phi = l(1); theta = l(2); psi = l(3);
R = [cos(theta)*cos(psi)...
      sin(phi)*sin(theta)*cos(psi)-cos(phi)*sin(psi)...
      cos(phi)*sin(theta)*cos(psi)+sin(phi)*sin(psi);
   cos(theta)*sin(psi)...
   sin(phi)*sin(theta)*sin(psi)+cos(phi)*cos(psi)... 
   cos(phi)*sin(theta)*sin(psi)-sin(phi)*cos(psi);
   -sin(theta)...
   sin(phi)*cos(theta)...
   cos(phi)*cos(theta)];
